### PR TITLE
Files browser in left panel and create file/folder function

### PR DESCRIPTION
**Pull request by martinfojtik**

### CODE REVIEW

**Comment by nournia** [comment]
This feature would be great.

**Comment by sdbarron** [comment]
@sveale Could you consider either approving this PR or make a comment as to why not (so someone could look into any issues you might be having)?  I'm _manually _using @fojtcz 's copy at the moment but I don't want to lose future fixes to your trunk if I don't have to.

**Comment by fojtcz** [comment]
@sveale i love to hear any suggestions
@sdbarron i'm using this every day and i will keep my PR up to date with main repository

**Comment by sveale** [comment]
I'll have a look at it. The thing is I've been working on some of the underlying architecture which makes the merge difficult. 

Sendt fra min iPhone

**Comment by sdbarron** [comment]
Thanks - that all I can ask!

**Comment by nikolakanacki** [comment]
I'm having problems getting any of the remote files to open. I just get a notification saying an error occurred while getting a file, and the tree view resets to the host root. Will investigate, this is definitely a nice idea.

**Pull request closed without merging**
